# Generated by Django 3.1.7 on 2021-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=6)),
                ('NAME', models.CharField(max_length=26)),
                ('OPEN', models.IntegerField()),
                ('HIGH', models.IntegerField()),
                ('LOW', models.IntegerField()),
                ('CLOSE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILURE')], default=0)),
            ],
        ),
    ]
