# Generated by Django 3.1.7 on 2021-04-12 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210411_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importdate',
            name='imported_date',
        ),
        migrations.AddField(
            model_name='importdate',
            name='imported_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.importdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importdetails',
            name='imported_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
